# -------------------------------------------------------------------------
# Description: 
# This script analyzes repeat elements in genomic data, focusing on their 
# divergence from consensus sequences. The analysis includes:
# 1. Loading repeat landscape data generated by EDTA.
# 2. Filtering and reshaping the data for visualization.
# 3. Categorizing repeat families (e.g., LTR/Copia, LTR/Gypsy, DNA transposons, MITEs).
# 4. Visualizing the divergence patterns using ggplot2.
#
# Key Functions:
# - It adjusts for inflated peaks caused by library sequences at low divergence.
# - Divergence is calculated as a percentage for better interpretability.
# - The resulting plot shows the sequence length of repeats (in Mbp) across 
#   divergence percentages, grouped by repeat family.
#
# Required Libraries:
# - reshape2
# - hrbrthemes
# - tidyverse
# - data.table
#
# Outputs:
# - A divergence plot saved as "Plots/output.pdf".
#
# Notes:
# - Ensure the input file path is correctly specified in the `data` variable.
# - Requires EDTA repeat landscape data file.
# -------------------------------------------------------------------------


library(reshape2)
library(hrbrthemes)
library(tidyverse)
library(data.table)


# get data from parameter
data <- "assembly.fasta.mod.EDTA.anno/assembly.fasta.mod.out.landscape.Div.Rname.tab"

rep_table <- fread(data, header = FALSE, sep = "\t")
rep_table %>% head()

colnames(rep_table) <- c("Rname", "Rclass", "Rfam", 1:50)
rep_table <- rep_table %>% filter(Rfam != "unknown")
rep_table$fam <- paste(rep_table$Rclass, rep_table$Rfam, sep = "/")

table(rep_table$fam)

rep_table.m <- melt(rep_table)

rep_table.m <- rep_table.m[-c(which(rep_table.m$variable == 1)), ] # remove the peak at 1, as the library sequences are copies in the genome, they inflate this low divergence peak

# Arrange the data so that they are in the following order:
# LTR/Copia, LTR/Gypsy, all types of DNA transposons (TIR transposons), DNA/Helitron, all types of MITES
rep_table.m$fam <- factor(rep_table.m$fam, levels = c(
  "LTR/Copia", "LTR/Gypsy", "DNA/DTA", "DNA/DTC", "DNA/DTH", "DNA/DTM", "DNA/DTT", "DNA/Helitron",
  "MITE/DTA", "MITE/DTC", "MITE/DTH", "MITE/DTM"
))

rep_table.m$distance <- as.numeric(rep_table.m$variable) / 100 # as it is percent divergence

# options(scipen = 999)

# remove helitrons as EDTA is not able to annotate them properly (https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A)
rep_table.m <- rep_table.m %>% filter(fam != "DNA/Helitron")

ggplot(rep_table.m, aes(fill = fam, x = distance, weight = value / 1000000)) +
  geom_bar() +
  cowplot::theme_cowplot() +
  scale_fill_brewer(palette = "Paired") +
  xlab("Distance") +
  ylab("Sequence (Mbp)") +
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 9, hjust = 1), plot.title = element_text(hjust = 0.5))

ggsave(filename = "Plots/output.pdf", width = 10, height = 5, useDingbats = F)
