#!/bin/bash
#SBATCH --time=6:00:00
#SBATCH --mem=64G
#SBATCH -p pibu_el8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=50
#SBATCH --job-name=Maker
#SBATCH --output=Maker_gene_annotation_%j.out
#SBATCH --error=Maker_gene_annotation_%j.err

# Running MAKER gene annotation pipeline with 50 parallel tasks
# Post-processing the output files by merging the GFF3 annotations and FASTA sequences.

module load OpenMPI/4.1.1-GCC-10.3.0
module load AUGUSTUS/3.4.0-foss-2021a

mkdir -p /data/users/tjanjumratsang/assembly_annotation_course/gene_annotation_directory

COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
WORKDIR=/data/users/tjanjumratsang/assembly_annotation_course/gene_annotation_directory
REPEATMASKER_DIR="/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"

# Set paths for MAKER control files
maker_opts=${COURSEDIR}/scripts/maker_opts.ctl
maker_bopts=${COURSEDIR}/scripts/maker_bopts.ctl
maker_evm=${COURSEDIR}/scripts/maker_evm.ctl
maker_exe=${COURSEDIR}/scripts/maker_exe.ctl

# Make control files executable
chmod +x *.ctl

cd $WORKDIR

# Add RepeatMasker to PATH for accessibility during the MAKER pipeline
export PATH=$PATH:"/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"

# Run the MAKER gene annotation pipeline inside an Apptainer container with MPI parallelism
mpiexec --oversubscribe -n 50 apptainer exec \
 --bind $SCRATCH:/TMP --bind $COURSEDIR --bind $AUGUSTUS_CONFIG_PATH --bind $REPEATMASKER_DIR \
 ${COURSEDIR}/containers/MAKER_3.01.03.sif \
 maker -mpi --ignore_nfs_tmp -TMP /TMP ${maker_opts} ${maker_bopts} ${maker_evm} ${maker_exe}
 
# Output preparation for final annotation files
COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
MAKERBIN="$COURSEDIR/softwares/Maker_v3.01.03/src/bin" 

# Merge GFF3 files generated by MAKER and save with new filenames
$MAKERBIN/gff3_merge -s -d assembly.maker.output/assembly_master_datastore_index.log > assembly.all.maker.gff 
$MAKERBIN/gff3_merge -n -s -d assembly.maker.output/assembly_master_datastore_index.log > assembly.all.maker.noseq.gff 

# Merge the FASTA files generated by MAKER into a single file
$MAKERBIN/fasta_merge -d assembly.maker.output/assembly_master_datastore_index.log -o assembly
